function input_array=input_feature_matrix(x_hori_re,y_hori_re,z_hori_re,...
    x_ver_re,y_ver_re,z_ver_re,...
    x_for_45_re,y_for_45_re,z_for_45_re,... 
    x_back_45_re,y_back_45_re,z_back_45_re,... 
    x_left_45_re,y_left_45_re,z_left_45_re,...
    x_right_45_re,y_right_45_re,z_right_45_re)


    input_array=cat(3,x_hori_re,y_hori_re,z_hori_re,...
    x_ver_re,y_ver_re,z_ver_re,...
    x_for_45_re,y_for_45_re,z_for_45_re,... 
    x_back_45_re,y_back_45_re,z_back_45_re,... 
    x_left_45_re,y_left_45_re,z_left_45_re,...
    x_right_45_re,y_right_45_re,z_right_45_re);






end