function poincare_sphere_arrange(S_HH,S_HV,S_VH,S_VV,f,window_size)

    S_HH_angle=angle(S_HH);
    S_HV_angle=angle(S_HV);
    S_VH_angle=angle(S_VH);
    S_VV_angle=angle(S_VV);
    index_distance=[];

    [x_hori_re,y_hori_re,z_hori_re,...
    x_ver_re,y_ver_re,z_ver_re,...
    x_for_45_re,y_for_45_re,z_for_45_re,... 
    x_back_45_re,y_back_45_re,z_back_45_re,... 
    x_left_45_re,y_left_45_re,z_left_45_re,...
    x_right_45_re,y_right_45_re,z_right_45_re]=poincare_sphere_plot(S_HH_angle,S_HV_angle,S_VH_angle,S_VV_angle,f,window_size,index_distance);

end